### ISSUE TITLE
Autoprefixer rails gem

### ISSUE THREAD

**Issue by zavalacl** [zavalacl/tc359_rails_final#2]
I added this to my gemfile but the instructions at https://github.com/ai/autoprefixer-rails got me confused. For example, where do I add these lines:

require "autoprefixer-rails"
prefixed = AutoprefixerRails.process(css, from: 'main.css').css

AutoprefixerRails.process(css, from: 'a.css', browsers: ['> 1%', 'ie 10']).css

**Comment by chrisvfritz** [comment]
That's just an example for advanced use. For basic use, all you have to do is add it the Gemfile and `bundle install`.
